package Project;

import javax.swing.JOptionPane;

public class StdRegistration extends javax.swing.JFrame {

    /**
     * Creates new form StdRegistration
     */
    public StdRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtFName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtContactNo = new javax.swing.JTextField();
        cmbGender = new javax.swing.JComboBox<>();
        txtGPA = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        txtRePassword = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setText("Student Registration Form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 6, -1, 35));

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 53, 170, -1));

        txtFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFNameKeyPressed(evt);
            }
        });
        getContentPane().add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 93, 170, -1));
        getContentPane().add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 133, 170, -1));

        txtContactNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContactNoKeyPressed(evt);
            }
        });
        getContentPane().add(txtContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 173, 170, -1));

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "        [--Select One--]", "Male", "Female" }));
        getContentPane().add(cmbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 213, 170, -1));

        txtGPA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtGPAKeyPressed(evt);
            }
        });
        getContentPane().add(txtGPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 253, 170, -1));
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 293, 170, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 53, -1, -1));

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 422, -1, -1));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 333, 170, -1));
        getContentPane().add(txtRePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 373, 170, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Father Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 93, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 133, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("GPA");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 253, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Gender");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 213, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Contact Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 173, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("User Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 293, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Password");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 333, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Confirm Password");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 373, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("F:\\Important Stuff\\Student Registration.jpg")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txtName.setText("");
        txtFName.setText("");
        txtAddress.setText("");
        txtContactNo.setText("");
        cmbGender.setSelectedIndex(0);
        txtGPA.setText("");
        txtUserName.setText("");
        txtPassword.setText("");
        txtRePassword.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Welcome wc=new Welcome();
        this.dispose();
        wc.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(txtName.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(StdRegistration.this,"Enter Data Correctly.");
            txtName.grabFocus();
            return;
        }
        if(txtFName.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(StdRegistration.this,"Enter Data Correctly.");
            txtFName.grabFocus();
            return;
        }
        if(txtAddress.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(StdRegistration.this,"Enter Data Correctly.");
            txtAddress.grabFocus();
            return;
        }
        if(txtContactNo.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(StdRegistration.this,"Enter Data Correctly.");
            txtContactNo.grabFocus();
            return;
        }
        if(cmbGender.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(StdRegistration.this,"Enter Data Correctly.");
            return;
        }
        if(txtGPA.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(StdRegistration.this,"Enter Data Correctly.");
            txtGPA.grabFocus();
            return;
        }
        if(txtUserName.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(StdRegistration.this,"Enter Data Correctly.");
            txtUserName.grabFocus();
            return;
        }
        if(txtPassword.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(StdRegistration.this,"Enter Data Correctly.");
            txtPassword.grabFocus();
            return;
        }
        if(txtRePassword.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(StdRegistration.this,"Enter Data Correctly.");
            txtRePassword.grabFocus();
            return;
        }
        if(txtRePassword.getText().equals(txtPassword.getText())){
            Student std=new Student();
            String name=txtName.getText();
            String fname=txtFName.getText();
            String adrs=txtAddress.getText();
            String cntno=txtContactNo.getText();
            String gen=(String) cmbGender.getSelectedItem();
            String gpa=txtGPA.getText();
            String uname=txtUserName.getText();
            String pswd=txtPassword.getText();
            std.addStudent(name, fname, adrs, cntno, gen, gpa, uname, pswd);
            JOptionPane.showMessageDialog(StdRegistration.this,"You have been Registered.");
        }
        else{
            JOptionPane.showMessageDialog(StdRegistration.this,"Enter Password Correctly.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtFNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFNameKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isDigit(c)){
            txtFName.setEditable(false);
            JOptionPane.showMessageDialog(StdRegistration.this, "Invalid Input!");
        }
        txtFName.setEditable(true);
    }//GEN-LAST:event_txtFNameKeyPressed

    private void txtContactNoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactNoKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            txtContactNo.setEditable(false);
            JOptionPane.showMessageDialog(StdRegistration.this, "Invalid Input!");
        }
        txtContactNo.setEditable(true);
    }//GEN-LAST:event_txtContactNoKeyPressed

    private void txtGPAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGPAKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isLetter(c)){
            txtGPA.setEditable(false);
            JOptionPane.showMessageDialog(StdRegistration.this, "Invalid Input!");
        }
        txtGPA.setEditable(true);
    }//GEN-LAST:event_txtGPAKeyPressed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(Character.isDigit(c)){
            txtName.setEditable(false);
            JOptionPane.showMessageDialog(StdRegistration.this, "Invalid Input!");
        }
        txtName.setEditable(true);
    }//GEN-LAST:event_txtNameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StdRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StdRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StdRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StdRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StdRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtGPA;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRePassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
